const express = require("express");
const router = express.Router();
const authRoutes = require("./auth");
const businessRoutes = require("./business");
const appointmentRoutes = require("./appointments");
const serviceRoutes = require("./services");
const clientRoutes = require("./client");
const featureSuggestionsRoutes = require("./featureSuggestions");
const notificationsRoutes = require("./notifications");
const promotionRoutes = require("./promotions");
const flashSaleRoutes = require("./flashSales");
const adminRoutes = require("./admin");
const supportRoutes = require("./support");
const apiKeyRoutes = require("./apiKeys");
const planRoutes = require("./plans");
const translateRoutes = require("./translate");
const creditsRoutes = require("./credits");
const barberRoutes = require("./barber");
const checkoutRoutes = require("./checkout");
const paymentRoutes = require("./payment");
const Auditing = require("./auditing");

router.use("/auth", authRoutes);
router.use("/business", businessRoutes);
router.use("/appointments", appointmentRoutes);
router.use("/services", serviceRoutes);
router.use("/client", clientRoutes);
router.use("/feature-suggestions", featureSuggestionsRoutes);
router.use("/notifications", notificationsRoutes);
router.use("/promotions", promotionRoutes);
router.use("/flash-sales", flashSaleRoutes);
router.use("/admin", adminRoutes);
router.use("/support", supportRoutes);
router.use("/admin/api-keys", apiKeyRoutes);
router.use("/plans", planRoutes);
router.use("/auditing", Auditing);
router.use("/translate", translateRoutes);
router.use("/credits", creditsRoutes);
router.use("/barber", barberRoutes);
router.use("/checkout", checkoutRoutes);
router.use("/payment", paymentRoutes);

module.exports = router;
